### ISSUE TITLE
Does it support encoding or decoding more data that OS can not allocate?

### ISSUE THREAD

**Issue by WWjsnt10** [mbitsnbites/liblzg#7]
Hi,
I want to decode the data with the LZ77.   However, the buffer length is 4096 and the length of data to be decoded is 1M.   1M Data will be divided into 4096 Bytes Block, which be sent.
Each time I can read the 4096 Bytes data and decode it and flash the data. I want to know if this lib can support it or how to modify the lib?

**Comment by mbitsnbites** [comment]
It would not work, unfortunately.

LZ works by copying previous occurances of strings, so the decoder needs to keep a sufficient amount of *decoded* data in memory in order to look up previous strings.

The most distant string offset supported by LZG is 526341, so you need to keep that many bytes in memory. In practice it means that you want to keep the entire decoded file in memory.

**Comment by WWjsnt10** [comment]
> It would not work, unfortunately.
> 
> LZ works by copying previous occurances of strings, so the decoder needs to keep a sufficient amount of _decoded_ data in memory in order to look up previous strings.
> 
> The most distant string offset supported by LZG is 526341, so you need to keep that many bytes in memory. In practice it means that you want to keep the entire decoded file in memory.

OK , Thanks , It may not be suitable for the embedded software!
